# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
resources:
  repositories:
  - repository: OneGitHubRepo 
    type: github
    endpoint: sks007
    name: sanks21/One
    
  
  - repository: TwoGitHubRepo 
    type: github
    endpoint: sks007
    name: sanks21/Two
    tag: refs/tags/v1.0

    
    
trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Import
  displayName: Import_files
  jobs:  
  - job: Import
    displayName: Imported_files
    pool:
      vmImage: ubuntu-latest
    
    steps:
    
    - checkout: TwoGitHubRepo
    
    - script: |
        git checkout main
        ls
        

        
        
        

        