# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


    
    
trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Import
  displayName: Import_files
  jobs:  
  - job: Import
    displayName: Imported_files
    pool:
      vmImage: ubuntu-latest
    
    steps:
    
    
    
    - script: |
        git clone https://github.com/sanks21/Two.git
        git clone https://github.com/sanks21/One.git
        ls
        cd Two
        ls
        cp * ../One
        cd ../One
        ls
        
        
        
        
        git config --global user.email "sks2296@gmail.com"
        git config --global user.name "sanks21"
        git add .
        git commit -m "import"
        git push https://$(GITHUBTOKEN)@github.com/sanks21/One.git main
        

        git checkout main
        a="$(git diff --name-only --diff-filter=AMCRT origin/Release_one...origin/main ':!azure-pipelines.yml')"
        echo "$a" > file1.txt
        
        
        
        mkdir importedzipfiles

        while read p; do
            echo "$p"
            cp "$p" importedzipfiles
        done <file1.txt

        
    
    - script: zip -r importedzipfiles.zip . -i importedzipfiles
    - task: CopyFiles@2
      inputs:
          Contents: "*zip"
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
    
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'Importedfiles'
        publishLocation: 'Container'
         
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
        

        