# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
  - repository: OneGitHubRepo 
    type: github
    endpoint: sks007
    name: sanks21/One
    
  
  - repository: TwoGitHubRepo 
    type: github
    endpoint: sks007
    name: sanks21/Two
    tag: refs/tags/v1.0
    
    
    
trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Import
  displayName: Import_files
  jobs:  
  - job: Import
    displayName: Imported_files
    pool:
      vmImage: ubuntu-latest
    
    steps:
    - checkout: OneGitHubRepo
    
    
    - script: |
        git checkout Release_one
        ls
        git clone https://github.com/sanks21/Two.git
        ls
        cd Two
        ls
        
        mkdir import 
        ls
        mv file1 import
        mv sks import
        ls
        cd Two
        ls
        git add .
        ls
        git commit
        ls

        git clone <git repository B url> # clone destination repository
        cd <git repository B directory>
        git remote add repo-A-branch <git repository A directory> # add source as a remote
        git pull repo-A-branch master # pull
        git remote rm repo-A-branch

        mkdir changedzipfiles

        while read p; do
            echo "$p"
            cp "$p" changedzipfiles
        done <file.txt

         
    
    - script: zip -r changedzipfiles.zip changedzipfiles
    
    

    
    - task: CopyFiles@2
      inputs:
          Contents: "*zip"
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'changedfiles'
        publishLocation: 'Container'
         
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'

    


