# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
  - repository: MyGitHubRepo 
    type: github
    endpoint: sks007
    name: sanks21/One
  
  - repository: MyGitHubRepo 
    type: github
    endpoint: sks007
    name: sanks21/Two

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: MyGitHubRepo

- script: dir $(Build.SourcesDirectory)
- script: dir $(Build.SourcesDirectory)