# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
  - repository: OneGitHubRepo 
    type: github
    endpoint: sks007
    name: sanks21/One
    
  
  - repository: TwoGitHubRepo 
    type: github
    endpoint: sks007
    name: sanks21/Two
    tag: refs/tags/v1.0
    
    
    
trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Import
  displayName: Import_files
  jobs:  
  - job: Import
    displayName: Imported_files
    pool:
      vmImage: ubuntu-latest
    
    steps:
    
    
    
    - script: |
        git checkout main
        ls
        cd ..
        ls
        git clone https://github.com/sanks21/Two.git
        ls
        
        cd Two
        ls
        cp file1 ./One
        cd One
        ls
        git config --global user.email "sks2296@gmail.com"
        git config --global user.name "sanks21"
        git add .
        git commit 
        git pull 
        git push -f
        
        

        mkdir changedzipfiles

        while read p; do
            echo "$p"
            cp "$p" changedzipfiles
        done <file.txt

         
    
    - script: zip -r changedzipfiles.zip changedzipfiles
    
    

    
    - task: CopyFiles@2
      inputs:
          Contents: "*zip"
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'changedfiles'
        publishLocation: 'Container'
         
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'