# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
  
  - repository: TwoGitHubRepo 
    type: github
    endpoint: sks007
    name: sanks21/Two
    ref: Release_Two
    
  

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Import
  displayName: Import_files
  jobs:  
  - job: Import
    displayName: Imported_files
    pool:
      vmImage: ubuntu-latest
    
    steps:
    - checkout: TwoGitHubRepo
    
    
    - script: |
        a="$(git branch -r)"
        echo "$a"
        git config --global user.email sks2296@gmail.com
        git config --global user.name sanks21
        c="$(git pull)"
        echo "$c" > file.txt

        mkdir changedzipfiles

        while read p; do
            echo "$p"
            cp "$p" changedzipfiles
        done <file.txt

         
    
    - script: zip -r changedzipfiles.zip changedzipfiles
    
    

    
    - task: CopyFiles@2
      inputs:
          Contents: "*zip"
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'changedfiles'
        publishLocation: 'Container'
         
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'

    


