# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
  - repository: OneGitHubRepo 
    type: github
    endpoint: sks007
    name: sanks21/One
    
  
  - repository: TwoGitHubRepo 
    type: github
    endpoint: sks007
    name: sanks21/Two
    tag: refs/tags/v1.0
    
    
    
trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Import
  displayName: Import_files
  jobs:  
  - job: Import
    displayName: Imported_files
    pool:
      vmImage: ubuntu-latest
    
    steps:
    - checkout: OneGitHubRepo
    
    
    - script: |
        git checkout Release_one
        ls
        git clone https://github.com/sanks21/Two.git temp-repo
        ls
        cd temp-repo
        ls
        git remote rm origin
        git rm -rf .
        git checkout HEAD -- sks
        git checkout HEAD -- file1
        git commit -m "move"
        git config --global user.email sks2296@gmail.com
        git config --global user.name sanks21
        git remote add origin https://github.com/sanks21/One.git
        git pull 
        git push -f

        mkdir changedzipfiles

        while read p; do
            echo "$p"
            cp "$p" changedzipfiles
        done <file.txt

         
    
    - script: zip -r changedzipfiles.zip changedzipfiles
    
    

    
    - task: CopyFiles@2
      inputs:
          Contents: "*zip"
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'changedfiles'
        publishLocation: 'Container'
         
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'

    


